# Generated by Django 4.2.6 on 2023-10-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Dress_code', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=250)),
                ('start_time', models.TimeField()),
            ],
        ),
    ]
