# Generated by Django 4.2.6 on 2023-10-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suncity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
