# Generated by Django 4.2.6 on 2023-10-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suncity', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='program',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
