# Generated by Django 5.0.1 on 2024-06-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suncity', '0007_program_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='program',
            name='Dress_code',
        ),
        migrations.RemoveField(
            model_name='program',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='program',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='program',
            name='name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='program',
            name='user',
        ),
    ]
