# Generated by Django 5.0.1 on 2024-06-27 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suncity', '0008_remove_program_date_remove_program_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='Date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='program',
            name='Description',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='program',
            name='Dress_code',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='Location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='start_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='program',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
