# Generated by Django 5.0.1 on 2024-06-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suncity', '0009_program_date_program_description_program_dress_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='user',
        ),
    ]
