# Generated by Django 5.0.1 on 2024-07-02 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suncity', '0012_alter_program_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='Date',
            field=models.DateField(default=None, help_text='year-month-day'),
        ),
        migrations.AlterField(
            model_name='program',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
