# Generated by Django 5.0.1 on 2024-10-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suncity', '0014_alter_program_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
